# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae2cdf58cfe493934c6d99fbd31967bb95a719f06945771bb290d21b02e397cd02222f7422c61e8feb6ff7c57e3812c94a79193782422d0c0762f129ec79292

test:
  secret_key_base: 3b13c24df8cabb8a5d216624885c8241f591ec839388bdae9dccef71a754aea29fd4047412fb3c780728755b3a2a6ba82babf000672e4e0e0229a5cbe47ebe23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
